//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDBCLM.DataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string CreationDate { get; set; }
    
        public virtual BlogPostCategory Category { get; set; }
    }
}
